import { useState, useCallback, useEffect, useRef, useMemo } from "react";
import { motion } from "framer-motion";
import { X, Copy, Check, FileCode, FileType, FileJson, Download, FolderOpen } from "lucide-react";
import { generateHTMLCode, generateCSSCode, generateJSCode, type WebsiteContent, type CustomStyles } from "@/lib/generateContent";
import JSZip from "jszip";
import { saveAs } from "file-saver";

interface CodeViewerProps {
  isOpen: boolean;
  onClose: () => void;
  content: WebsiteContent;
  customStyles: CustomStyles;
}

const LINE_HEIGHT = 21;
const OVERSCAN = 30;

const CodeViewer = ({ isOpen, onClose, content, customStyles }: CodeViewerProps) => {
  const [activeFile, setActiveFile] = useState<"html" | "css" | "js">("html");
  const [copied, setCopied] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const [scrollTop, setScrollTop] = useState(0);
  const [viewHeight, setViewHeight] = useState(800);

  const htmlCode = useMemo(() => generateHTMLCode(content, customStyles), [content, customStyles]);
  const cssCode = useMemo(() => generateCSSCode(content, customStyles), [content, customStyles]);
  const jsCode = useMemo(() => generateJSCode(), []);

  const codeMap = useMemo(() => ({ html: htmlCode, css: cssCode, js: jsCode }), [htmlCode, cssCode, jsCode]);

  const lines = useMemo(() => codeMap[activeFile].split('\n'), [codeMap, activeFile]);
  const lineCount = lines.length;

  const totalHeight = lineCount * LINE_HEIGHT;
  const startLine = Math.max(0, Math.floor(scrollTop / LINE_HEIGHT) - OVERSCAN);
  const endLine = Math.min(lineCount, Math.ceil((scrollTop + viewHeight) / LINE_HEIGHT) + OVERSCAN);
  const visibleLines = lines.slice(startLine, endLine);
  const offsetY = startLine * LINE_HEIGHT;

  const handleScroll = useCallback(() => {
    if (scrollRef.current) {
      setScrollTop(scrollRef.current.scrollTop);
    }
  }, []);

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    const ro = new ResizeObserver(() => setViewHeight(el.clientHeight));
    ro.observe(el);
    return () => ro.disconnect();
  }, [isOpen]);

  useEffect(() => {
    setScrollTop(0);
    if (scrollRef.current) scrollRef.current.scrollTop = 0;
  }, [activeFile]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(codeMap[activeFile]);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [codeMap, activeFile]);

  const handleCopyAll = useCallback(() => {
    const allCode = `${htmlCode}\n\n${cssCode}\n\n${jsCode}`;
    navigator.clipboard.writeText(allCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [htmlCode, cssCode, jsCode]);

  const handleExport = useCallback(() => {
    const zip = new JSZip();
    zip.file("index.html", codeMap.html);
    zip.file("style.css", codeMap.css);
    zip.file("script.js", codeMap.js);
    zip.file("README.md", `# ${content.siteName}\n\nGenerated by AI Website Builder\n\n## How to use\n1. Open index.html in your browser\n2. Edit the files to customize\n3. Deploy anywhere!\n`);
    zip.generateAsync({ type: "blob" }).then(blob => {
      saveAs(blob, `${content.siteName.toLowerCase().replace(/\s+/g, '-')}-website.zip`);
    });
  }, [codeMap, content.siteName]);

  const fileLabels: { id: "html" | "css" | "js"; label: string; icon: React.ReactNode; color: string }[] = [
    { id: "html", label: "index.html", icon: <FileCode className="w-4 h-4" />, color: "#e34c26" },
    { id: "css", label: "style.css", icon: <FileType className="w-4 h-4" />, color: "#264de4" },
    { id: "js", label: "script.js", icon: <FileJson className="w-4 h-4" />, color: "#f0db4f" },
  ];

  useEffect(() => {
    if (!isOpen) return;
    const handleKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[110] flex flex-col" style={{ background: "#0d1117" }}>
      <div className="flex items-center justify-between px-4 py-3 border-b border-white/10 shrink-0" style={{ background: "#161b22" }}>
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <button type="button" onClick={onClose} className="w-3 h-3 rounded-full bg-red-500 hover:brightness-110 cursor-pointer border-0 p-0" aria-label="Close" />
            <div className="w-3 h-3 rounded-full bg-yellow-500" />
            <div className="w-3 h-3 rounded-full bg-green-500" />
          </div>
          <span className="text-sm font-semibold text-white/70 ml-2">
            {content.siteName} — Source Code
          </span>
        </div>
        <div className="flex items-center gap-2">
          <button type="button" onClick={handleCopyAll}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-white/60 hover:text-white hover:bg-white/10 transition-all">
            <Copy className="w-3.5 h-3.5" /> Copy All
          </button>
          <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
            type="button" onClick={handleExport}
            className="flex items-center gap-1.5 px-4 py-1.5 rounded-lg text-xs font-semibold bg-green-600 text-white hover:bg-green-500 transition-colors">
            <Download className="w-3.5 h-3.5" /> Export ZIP
          </motion.button>
          <button type="button" onClick={onClose}
            className="p-2 rounded-lg text-white/60 hover:text-white hover:bg-white/10 transition-all ml-2" aria-label="Close code viewer">
            <X className="w-5 h-5" />
          </button>
        </div>
      </div>

      <div className="flex" style={{ height: "calc(100vh - 52px)" }}>
        <div className="w-56 border-r border-white/10 py-4 hidden sm:block shrink-0 overflow-y-auto" style={{ background: "#0d1117" }}>
          <div className="flex items-center gap-2 px-4 mb-4">
            <FolderOpen className="w-4 h-4 text-blue-400" />
            <span className="text-xs font-bold text-white/50 uppercase tracking-wider">Files</span>
          </div>
          {fileLabels.map(f => (
            <button key={f.id} type="button" onClick={() => setActiveFile(f.id)}
              className={`w-full flex items-center gap-3 px-4 py-2.5 text-sm transition-all ${
                activeFile === f.id
                  ? "bg-white/10 text-white border-l-2"
                  : "text-white/50 hover:text-white/80 hover:bg-white/5 border-l-2 border-transparent"
              }`}
              style={activeFile === f.id ? { borderColor: f.color } : undefined}>
              <span style={{ color: f.color }}>{f.icon}</span>
              {f.label}
            </button>
          ))}
          <div className="mt-6 px-4">
            <div className="text-[10px] text-white/30 uppercase tracking-wider mb-2">Info</div>
            <div className="text-xs text-white/40 space-y-1">
              <p>{lineCount} lines</p>
              <p>{(codeMap[activeFile].length / 1024).toFixed(1)} KB</p>
            </div>
          </div>
        </div>

        <div className="flex-1 flex flex-col min-w-0" style={{ height: "100%" }}>
          <div className="flex sm:hidden border-b border-white/10 w-full shrink-0" style={{ background: "#161b22" }}>
            {fileLabels.map(f => (
              <button key={f.id} type="button" onClick={() => setActiveFile(f.id)}
                className={`flex-1 flex items-center justify-center gap-1.5 py-2.5 text-xs font-medium transition-all border-b-2 ${
                  activeFile === f.id
                    ? "text-white bg-white/5"
                    : "text-white/40 hover:text-white/60"
                }`}
                style={activeFile === f.id ? { borderColor: f.color } : { borderColor: 'transparent' }}>
                <span style={{ color: f.color }}>{f.icon}</span>
                <span className="hidden xs:inline">{f.label}</span>
              </button>
            ))}
          </div>

          <div className="flex items-center justify-between px-4 py-2 border-b border-white/5 shrink-0" style={{ background: "#0d1117" }}>
            <div className="flex items-center gap-2">
              <span style={{ color: fileLabels.find(f => f.id === activeFile)?.color }}>
                {fileLabels.find(f => f.id === activeFile)?.icon}
              </span>
              <span className="text-sm font-medium text-white/70">{fileLabels.find(f => f.id === activeFile)?.label}</span>
            </div>
            <button type="button" onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1 rounded-md text-xs font-medium bg-white/10 text-white/70 hover:bg-white/15 hover:text-white transition-all">
              {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>

          <div
            ref={scrollRef}
            onScroll={handleScroll}
            className="cv-scroll"
            style={{
              flex: 1,
              overflow: "auto",
              scrollbarWidth: "thin",
              scrollbarColor: "#3b82f680 #0d1117",
            }}
          >
            <style>{`
              .cv-scroll::-webkit-scrollbar { width: 12px; height: 12px; }
              .cv-scroll::-webkit-scrollbar-track { background: #0d1117; }
              .cv-scroll::-webkit-scrollbar-thumb { background: #3b82f660; border-radius: 6px; border: 3px solid #0d1117; }
              .cv-scroll::-webkit-scrollbar-thumb:hover { background: #3b82f6; }
              .cv-scroll::-webkit-scrollbar-corner { background: #0d1117; }
            `}</style>
            <div style={{ height: totalHeight, position: "relative" }}>
              <div style={{ position: "absolute", top: offsetY, left: 0, right: 0 }} className="flex">
                <div className="py-0 pr-4 pl-4 select-none shrink-0 hidden md:block sticky left-0 z-10" style={{ minWidth: '3.5rem', background: '#0d1117' }}>
                  {visibleLines.map((_, i) => (
                    <div key={startLine + i} className="text-right text-[12px] leading-[21px] font-mono" style={{ color: 'rgba(255,255,255,0.15)' }}>
                      {startLine + i + 1}
                    </div>
                  ))}
                </div>
                <pre className="py-0 pr-6 pl-4 md:pl-0">
                  <code className="text-[13px] leading-[21px] font-mono text-[#e6edf3] whitespace-pre">
                    {visibleLines.join('\n')}
                  </code>
                </pre>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CodeViewer;
